basePath: /douyin/v2/
definitions:
  comment.Comment:
    properties:
      content:
        description: 评论内容
        type: string
      create_date:
        description: 评论发布日期, 格式 mm-dd
        type: string
      id:
        description: 视频评论id
        type: string
      user:
        allOf:
        - $ref: '#/definitions/common.User'
        description: 评论用户信息
    type: object
  comment.CommentActionReq:
    properties:
      action_type:
        description: 1-发布评论, 2-删除评论
        type: integer
      comment_id:
        description: 要删除的评论id，在action_type=2的时候使用
        type: string
      comment_text:
        description: optional string comment_text = 4; // 用户填写的评论内容，在action_type=1的时候使用
        type: string
      hash_id:
        description: 视频hashId
        type: string
      token_info:
        allOf:
        - $ref: '#/definitions/common.TokenInfoReq'
        description: tokenInfo
      video_id:
        description: 视频id
        type: integer
    required:
    - action_type
    - hash_id
    type: object
  comment.CommentListResp:
    properties:
      comment_list:
        description: 评论列表
        items:
          $ref: '#/definitions/comment.Comment'
        type: array
      page:
        description: 页数
        type: integer
      page_size:
        description: 每页记录数
        type: integer
      total:
        description: 总记录数
        type: integer
      total_page:
        description: 总页数
        type: integer
    type: object
  common.TokenInfoReq:
    properties:
      id:
        description: 用户id
        type: integer
      username:
        description: 用户名
        type: string
    type: object
  common.User:
    properties:
      favorite_count:
        description: 点赞数量
        type: integer
      id:
        description: 用户id
        type: string
      name:
        description: 用户名称
        type: string
      work_count:
        description: 作品数量
        type: integer
    type: object
  common.Video:
    properties:
      author:
        allOf:
        - $ref: '#/definitions/common.User'
        description: 视频作者信息
      comment_count:
        description: 视频的评论总数
        type: integer
      cover_url:
        description: 视频封面地址
        type: string
      favoriteCount:
        description: 视频的点赞总数
        type: integer
      id:
        description: 视频唯一标识
        type: string
      is_favorite:
        description: true-已点赞, false-未点赞
        type: boolean
      play_url:
        description: 视频播放地址
        type: string
      title:
        description: 视频标题
        type: string
    type: object
  common.VideoListResp:
    properties:
      page:
        description: 页数
        type: integer
      page_size:
        description: 每页记录数
        type: integer
      total:
        description: 总记录数
        type: integer
      total_page:
        description: 总页数
        type: integer
      video_list:
        description: 视频列表
        items:
          $ref: '#/definitions/common.Video'
        type: array
    type: object
  favorite.FavoriteActionReq:
    properties:
      action_type:
        description: 1-点赞, 2-取消点赞
        type: integer
      hash_id:
        description: 视频hashId
        type: string
      token_info:
        allOf:
        - $ref: '#/definitions/common.TokenInfoReq'
        description: tokenInfo
      video_id:
        description: 视频id
        type: integer
    required:
    - action_type
    - hash_id
    type: object
  user.NormalizeUserReq:
    properties:
      password:
        description: 登录密码, 最长32个字符
        maxLength: 32
        type: string
      username:
        description: 用户名, 最长32个字符
        maxLength: 32
        type: string
    required:
    - password
    - username
    type: object
  user.UserLoginResp:
    properties:
      hash_id:
        type: string
      token:
        type: string
    type: object
  user.UserRegisterResp:
    properties:
      hash_id:
        type: string
      token:
        type: string
    type: object
  video.VideoFeedResp:
    properties:
      next_time:
        description: 本次返回的视频中，发布最早的时间，作为下次请求时的latest_time
        type: integer
      video_list:
        description: 视频列表
        items:
          $ref: '#/definitions/common.Video'
        type: array
    type: object
info:
  contact: {}
  description: 简易版抖音 2.0 后台接口
  title: 简易版抖音 2.0 后台接口
  version: "2.0"
paths:
  /comment/action:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 评论操作
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/comment.CommentActionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comment.Comment'
      summary: 评论操作
      tags:
      - 评论相关
  /comment/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 评论列表
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 视频hashId
        in: query
        name: hash_id
        required: true
        type: string
      - description: 页数
        in: query
        name: page
        type: integer
      - description: 每页记录数
        in: query
        name: page_size
        type: integer
      - description: 视频id
        in: query
        name: video_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/comment.CommentListResp'
      summary: 评论列表
      tags:
      - 评论相关
  /favorite/action:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 赞操作
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/favorite.FavoriteActionReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 赞操作
      tags:
      - 赞相关
  /favorite/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 点赞列表
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户hashId
        in: query
        name: hash_id
        required: true
        type: string
      - description: 用户id
        in: query
        name: user_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/common.Video'
            type: object
      summary: 点赞列表
      tags:
      - 赞相关
  /feed:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 视频流
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 可选参数, 限制返回视频的最新投稿时间戳, 精确到秒, 不填表示当前时间
        in: query
        name: latest_time
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/video.VideoFeedResp'
      summary: 视频流
      tags:
      - 视频相关
  /publish/action/:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 视频投稿
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: 文件
        in: formData
        name: data
        required: true
        type: file
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: 视频投稿
      tags:
      - 视频相关
  /publish/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 发布列表
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - description: 用户hash_id
        in: query
        name: hash_id
        required: true
        type: string
      - description: 排序规则, order=规则1,规则2, ......
        in: query
        name: order
        type: string
      - description: 页数
        in: query
        name: page
        type: integer
      - description: 每页记录数
        in: query
        name: page_size
        type: integer
      - description: '排序方式, -1: 倒序, 1: 正序 默认倒序'
        in: query
        name: sort
        type: integer
      - description: 用户id
        in: query
        name: user_id
        type: integer
      - description: 条件, where=条件1:值1,条件2:值2, ......
        in: query
        name: where
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/common.VideoListResp'
      summary: 发布列表
      tags:
      - 视频相关
  /user:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户信息
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - collectionFormat: csv
        description: 用户hashId
        in: query
        items:
          type: string
        name: hash_ids
        required: true
        type: array
      - collectionFormat: csv
        description: 用户id
        in: query
        items:
          type: integer
        name: user_ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/common.User'
            type: object
      summary: 用户信息
      tags:
      - 用户相关
  /user/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户登录
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.NormalizeUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserLoginResp'
      summary: 用户登录
      tags:
      - 用户相关
  /user/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 用户注册
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.NormalizeUserReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.UserRegisterResp'
      summary: 用户注册
      tags:
      - 用户相关
  /video:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 视频信息
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        type: string
      - collectionFormat: csv
        description: 视频hash_id
        in: query
        items:
          type: string
        name: hash_ids
        required: true
        type: array
      - collectionFormat: csv
        description: 视频id
        in: query
        items:
          type: integer
        name: video_ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              $ref: '#/definitions/common.Video'
            type: object
      summary: 视频信息
      tags:
      - 视频相关
schemes:
- http
swagger: "2.0"
