info:
  contact: {}
paths:
  /feed:
    get:
      parameters:
      - description: latest_time
        in: query
        name: latest_time
        type: string
      - description: token
        in: query
        name: token
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 视频流
      tags:
      - 基础接口
  /hello:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 首页
      tags:
      - 公共接口
  /publish/action/:
    post:
      parameters:
      - description: token
        in: formData
        name: token
        required: true
        type: string
      - description: 文件
        in: formData
        name: data
        required: true
        type: file
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 视频投稿
      tags:
      - 基础接口
swagger: "2.0"
